#!/usr/bin/env python3
"""Merge drop-in addon module manifests into a single !include target.

Run once at container startup (see docker-entrypoint.sh), before the gateway
reads routes.yaml. Scans ADDONS_DIR for *.yaml/*.yml files (each containing
either one module map or a YAML list of module maps — the same shape
!include already accepts), concatenates them, and writes the combined list
to ADDONS_OUTPUT. routes.yaml has a single permanent line:

    - !include data/_addons_generated.yaml

so routes.yaml itself never needs to change when addons are added, removed,
or edited — only the files under ADDONS_DIR do.

The output file is ALWAYS written, even when no addon files are present
(as an empty list), so the !include in routes.yaml never fails with
FileNotFoundError.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import yaml

ADDONS_DIR = Path(os.environ.get("ADDONS_DIR", "/app/addons"))
ADDONS_OUTPUT = Path(os.environ.get("ADDONS_OUTPUT", "/app/data/_addons_generated.yaml"))

# Skip reserved/template/backup files so authors can keep a copy-paste
# example in the same folder without it being loaded as a real module.
_SKIP_SUFFIXES = (".example", ".disabled", ".bak")


def _iter_addon_files() -> list[Path]:
    if not ADDONS_DIR.is_dir():
        return []
    files = [
        p
        for p in ADDONS_DIR.iterdir()
        if p.is_file()
        and p.suffix.lower() in (".yaml", ".yml")
        and not p.name.startswith("_")
        and not any(p.name.endswith(suf) for suf in _SKIP_SUFFIXES)
    ]
    return sorted(files)


def main() -> int:
    modules: list[dict] = []
    loaded_names: list[str] = []

    for path in _iter_addon_files():
        try:
            data = yaml.safe_load(path.read_text(encoding="utf-8"))
        except yaml.YAMLError as e:
            print(f"[merge_addon_routes] ERROR parsing {path}: {e}", file=sys.stderr)
            return 1

        if data is None:
            continue  # empty file — ignore
        elif isinstance(data, list):
            modules.extend(data)
            loaded_names.extend(m.get("name", "?") for m in data if isinstance(m, dict))
        elif isinstance(data, dict):
            modules.append(data)
            loaded_names.append(data.get("name", "?"))
        else:
            print(
                f"[merge_addon_routes] ERROR {path}: expected a module map or "
                f"list of module maps, got {type(data).__name__}",
                file=sys.stderr,
            )
            return 1

    ADDONS_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Auto-generated by scripts/merge_addon_routes.py at container startup.\n"
        "# DO NOT EDIT — edit files under ./addons/ instead, then restart the\n"
        "# container. See ./addons/README.md.\n"
    )
    with ADDONS_OUTPUT.open("w", encoding="utf-8") as f:
        f.write(header)
        yaml.safe_dump(modules, f, sort_keys=False)

    if loaded_names:
        print(f"[merge_addon_routes] loaded {len(loaded_names)} addon module(s): {', '.join(loaded_names)}")
    else:
        print("[merge_addon_routes] no addon modules found — nothing to merge")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
